### ISSUE TITLE
fix libuser log format

### ISSUE THREAD

**Issue by Orycterope** [sunriseos/SunriseOS#145]
The [INFO]  appears on the fist line, but not on the following ones. 

![screenshot](https://user-images.githubusercontent.com/6343527/51122027-30979400-1819-11e9-97a5-a509179e9d8f.png)

Also, it would be nice if the service's name (sm, shell, ahci) could have a fixed padding, to align everything.

**Comment by roblabla** [comment]
Ideally, we should add a custom syscall for logging: `fn syscall_log(level: u8, module: &str, data: &str)`. It would use the `log!` macro to generate the following output:

`[Level] - module - process - data`

**Comment by roblabla** [comment]
Almsot completely fixed. We don't pad service name.
