### ISSUE TITLE
Find a proper name for KFS OS and Kernel

### ISSUE THREAD

**Issue by roblabla** [sunriseos/SunriseOS#197]
KFS is pretty uninspired. We need something better.

Atmosphere-NX has some really cool names with nice metaphores. The different parts of the OS are named after atmosphere layers (exosphere, thermosphere, stratosphere, troposphere, mesosphere), and the bootloader is a rocket (fusee).

Another example is Fuchsia, which uses precious metals for its component names (zircon, topaz, peridot, garnet).

@Orycterope had the idea to call the OS "Sunrise", after the SynthWave sunrise imagery. ![Sun Rise Synthwave](https://d2tml28x3t0b85.cloudfront.net/tracks/artworks/000/628/933/original/bf22fb.jpeg?1506702399)

Is there more common symbols in the Synthwave culture we could use to name the various components? Any other cool ideas?

**Comment by Orycterope** [comment]
carlOS ... sweet carlos 😌

**Comment by roblabla** [comment]
SunriseOS it is. Now we just need to rename all the old KFS stuff.
