### ISSUE TITLE
documentation on github pages is broken

### ISSUE THREAD

**Issue by Orycterope** [sunriseos/SunriseOS#210]
Our [documentation](https://roblabla42.github.io/KFS/master/)'s index page:

![Screenshot_20190312_215632](https://user-images.githubusercontent.com/6343527/54235546-bc742680-4511-11e9-8513-96364fdab289.png)

Links are broken too. 

It's been like that since a days.

**Comment by roblabla** [comment]
Not the case anymore: https://sunriseos.github.io/SunriseOS/master/

I believe this was due to a rustdoc bug. Closing.
