### ISSUE TITLE
userspace.ld stores .bss in the ELF

### ISSUE THREAD

**Issue by Orycterope** [sunriseos/SunriseOS#216]
Rejoice, it's that "loosing all sanity while screaming at lld" time again !
I know you missed it.

Here's the problem: 

I create a really big array (32M) in vi:
```rust 
// UHD 4K resolution, lives in the .bss
static BACKBUFFER_ARR: Mutex<[VBEColor; (3840 * 2160)]> = Mutex::new([VBEColor::rgb(0, 0, 0); 3840 * 2160]);
```
compile it, make sure that it actually is in the .bss
```shell
$ nm -S kfs-vi | grep BACKBUFFER
00455030 01fa4001 b _ZN6kfs_vi14BACKBUFFER_ARR17he562314c92e24f7eE
```
mmmh 'b' so it's in the .bss, and 0x1fa4001 is the right size. 

Oh Great ! Everything works perf-

```shell
$ ls -lh kfs-vi
-rwxr-xr-x 1 orycterope orycterope  36M Mar 13 23:03 kfs-vi
```

Oh no ...

.... .... how ... i mean ... how ... what ??

Ok maybe roblabla fucked up `userspace.ld`, and it just doesn't put the .bss as NOBITS ?

```shell
$ readelf -S kfs-vi
Section Headers:
  [Nr] Name              Type            Addr     Off    Size   ES Flg Lk Inf Al
  ...
  [ 6] .data             PROGBITS        00455000 055000 000030 00  WA  0   0  4
  [ 7] .dynamic          NOBITS          00455030 055030 000000 00  WA  0   0  1
  [ 8] .bss              NOBITS          00455030 055030 1fa4148 00  WA  0   0  4
  [ 9] .kernel_caps      PROGBITS        023f9178 1ff9178 000018 00   A  0   0  4
  [10] .kernel_ioports   NOBITS          023f9190 1ff9190 000000 00   A  0   0  1
  [11] .comment          PROGBITS        00000000 1ff9190 000012 01  MS  0   0  1
```

Nope. Wait =_= ... WHAAAAAT ???

Ok so .bss **is** NOBITS, it has a plausible size, but notice how it increments file offsets by exactly its size, where every other NOBITS section does not shift it. This means that .bss is correctly registered as NOBITS, but still stored in the ELF.

This seems to be confirmed by objdump's section hexdump:
```shell
$ objdump -j .data -s kfs-vi

isofiles/boot/kfs-vi:     file format elf32-i386

Contents of section .data:
 455000 00000000 04000000 00000000 00000000  ................
 455010 70484400 00000000 01000000 f0414400  pHD..........AD.
 455020 20424400 40424400 70913f02 10504500   BD.@BD.p.?..PE.
```
```shell
$ objdump -j .bss -s kfs-vi

isofiles/boot/kfs-vi:     file format elf32-i386

objdump: section '.bss' mentioned in a -j option, but not found in any input file
```

However, if .bss truly was a NOBITS section, its PT_LOAD segment should have a lower file size than destination memory size, and the difference (padding) should be filled with zeros. That's what we have in kfs-kernel. But here:
```shell
$ readelf -l kfs-vi

Elf file type is EXEC (Executable file)
Entry point 0x43cfa0
There are 3 program headers, starting at offset 52

Program Headers:
  Type           Offset   VirtAddr   PhysAddr   FileSiz MemSiz  Flg Align
  PHDR           0x000034 0x00400034 0x00400034 0x00060 0x00060 R   0x4
  LOAD           0x000000 0x00400000 0x00400000 0x1ff9190 0x1ff9190 RWE 0x1000
  GNU_STACK      0x000000 0x00000000 0x00000000 0x00000 0x00000 RW  0

 Section to Segment mapping:
  Segment Sections...
   00
   01     .text .rodata .eh_frame .debug_gdb_scripts .eh_frame_hdr .data .dynamic .bss .kernel_caps
   02
```

FileSize == MemSize. So the content of the file is still copied to memory, and there's no bzeroed padding. I don't think I can believe in anything after that.

Also, I've checked in xxd, to see what the ELF stores at .bss' offset : 
```
.data 00055000: 0000 0000 0400 0000 0000 0000 0000 0000  ................
      00055010: 7048 4400 0000 0000 0100 0000 f041 4400  pHD..........AD.
      00055020: 2042 4400 4042 4400 7091 3f02 1050 4500   BD.@BD.p.?..PE.
.bss  00055030: 0000 0000 0000 0000 0000 0000 0000 0000  ................
      00055040: 0000 0000 0000 0000 0000 0000 0000 0000  ................
      00055050: 0000 0000 0000 0000 0000 0000 0000 0000  ................
      00055060: 0000 0000 0000 0000 0000 0000 0000 0000  ................
      ...
```

Bunch of zeros ... great

**Comment by Orycterope** [comment]
Also note that .text, .rodata and .data all end up in a single PT_LOAD segment, which is RWE. This is really bad for security.

**Comment by roblabla** [comment]
> Also note that .text, .rodata and .data all end up in a single PT_LOAD segment, which is RWE. This is really bad for security.

Wait what? I thought I fixed that? God fucking damnit LLD.

**Comment by Orycterope** [comment]
> > Also note that .text, .rodata and .data all end up in a single PT_LOAD segment, which is RWE. This is really bad for security.
> 
> Wait what? I thought I fixed that? God fucking damnit LLD.

I can't find any documentation on half of the function you use for segments. Especially:
```
  . = SEGMENT_START("text-segment", 0x400000) + SIZEOF_HEADERS;
```
```
  . = ALIGN(CONSTANT (MAXPAGESIZE));
```
```
  . = DATA_SEGMENT_ALIGN (CONSTANT (MAXPAGESIZE), CONSTANT (COMMONPAGESIZE));
```

Plus the fact that we never declare any segments.

**Comment by Orycterope** [comment]
> The linker will create reasonable program headers by default. 
When the linker sees the PHDRS command in the linker script, it will not create any program headers other than the ones specified.
https://sourceware.org/binutils/docs/ld/PHDRS.html#PHDRS

Ok so no PHDRS means we get default segments, as vague as this can be.

I didn't know that. Not sure this is ideal ...

**Comment by Orycterope** [comment]
.text (and following sections) never gets assigned explicitly to a segment. I can't find anywhere in the doc what its implicit segment should be. Maybe we should explicitly map it to a :text segment, and see if it changes anything ...

**Comment by Thog** [comment]
Close by #247
