### ISSUE TITLE
xmas_elf OOB access in Kernel ELF loader

### ISSUE THREAD

**Issue by Thog** [sunriseos/SunriseOS#374]
This memory corruption only occurs while loading vi and can be reproduced on PR #360 .

**Comment by roblabla** [comment]
https://github.com/sunriseos/SunriseOS/pull/360/commits/d9c80bfecae0080b0bd3f69b5a2763a34ceaec06 is the commit that's affected (in case PR gets force pushed)

**Comment by Orycterope** [comment]
Can you give a description of the problem ?

**Comment by Orycterope** [comment]
This bug is definitely present on master.
 
Haven't bisect yet, but reverting last xmas_elf update fixes the problem: 014dc189 (Jun 15 !)

I would like to investigate and report the bug to xmas_elf, but in the mean time I'm going to make a PR doing the revert.

**Comment by Orycterope** [comment]
I was wrong, reverting xmas_elf update does no solve the problem. On some branches it seems to sometime disappear when doing a full rebuild of sunrise, hinting toward an incremental compilation problem.

For now I still believe this is a xmas_elf bug, and sunrise is not responsible for it. To prove my theory I'm going to try to replicate the OOB in a std crate that just tries to parse the "faulty" vi elf with xmas_elf.

**Comment by roblabla** [comment]
@Thog found the problem: it's in mkiso-rs.

Once the bug is found, we should add a test to the CI that the generated ISO is correct by mounting the ISO and checking all the files.

**Comment by Thog** [comment]
GRUB2 seems to not like the way my files were allocated, this should be fixed by the last release of mkisofs-rs. Please make sure to update it.

**Comment by Orycterope** [comment]
Updated mkisofs-rs, diffed every module loaded by grub against their original elf, everything seems to be in order now. 

I'm closing the issue.
