### ISSUE TITLE
Detect usage of SpinLock in IRQ context

### ISSUE THREAD

**Issue by roblabla** [sunriseos/SunriseOS#471]
It'd be nice if we could detect use of a SpinLock in an IRQ context. Such usage would be wrong (since it might end up deadlocking the CPU). @Orycterope I wonder if we could set a global boolean or something in an IRQ, and check it when locking a SpinLock, panicking if it's set?

**Comment by Orycterope** [comment]
Mmmh spinlock is allowed in interrupt context, it's even recommended in an SMP system, where two irqs on two separate core might be fighting for the same resource ! As long as you don't share its usage across interrupt context boundary, it will never deadlock, as irqs will never be interrupted again. 

See doc rules in /kernel/sync/mutex.rs

**Comment by Orycterope** [comment]
Oh wait, just read my own docs again, and you're right, there's no point to a spinlock in IC.

**Comment by roblabla** [comment]
needs more jpeg.
